/**
 * src/components/studentSide/projectView/types/sectionTypes.js
 *
 * Section registry for the modular project view system.
 * Defines all available sections, their configuration, and rendering order.
 * Sections are rendered in a consistent order regardless of when the user enables them.
 */

// =============================================================================
// SECTION ZONES - Define where sections render in the layout
// =============================================================================

export const ZONES = {
  HERO: 'hero',       // Top banner area
  SIDEBAR: 'sidebar', // Left column cards
  MAIN: 'main',       // Right column (poster area)
  FOOTER: 'footer',   // Bottom banner
};

// =============================================================================
// SECTION DEFINITIONS
// =============================================================================

/**
 * Master section registry
 * - order: Determines rendering order (lower = earlier)
 * - mandatory: If true, section is always included and cannot be disabled
 * - zone: Where the section renders in the layout
 * - formOrder: Order in the form (may differ from display order)
 * - config: Section-specific configuration options
 */
export const SECTIONS = {
  // === MANDATORY SECTIONS ===
  HERO: {
    id: 'hero',
    name: 'Project Overview',
    description: 'Title, description, and category label',
    mandatory: true,
    order: 0,
    formOrder: 0,
    zone: ZONES.HERO,
    icon: 'mdi-text-box-outline',
  },

  AUTHORS: {
    id: 'authors',
    name: 'Author(s)',
    description: 'Project contributors with photos and testimonials',
    mandatory: true,
    order: 1,
    formOrder: 1,
    zone: ZONES.HERO,
    icon: 'mdi-account-outline',
    config: {
      minAuthors: 1,
      maxAuthors: 6,
    },
  },

  TAGS: {
    id: 'tags',
    name: 'Project Tags',
    description: 'Keywords that describe your project',
    mandatory: true,
    order: 10,
    formOrder: 2,
    zone: ZONES.SIDEBAR,
    icon: 'mdi-tag-multiple-outline',
    config: {
      minTags: 1,
      maxTags: 10,
    },
  },

  FINDINGS: {
    id: 'findings',
    name: 'Key Findings',
    description: 'Highlight 1-3 key statistics or achievements with a conclusion',
    mandatory: false,
    order: 20,
    formOrder: 3,
    zone: ZONES.SIDEBAR,
    icon: 'mdi-chart-box-outline',
    config: {
      minItems: 1,
      maxItems: 3,
      includesConclusion: true,
    },
  },

  FOOTER: {
    id: 'footer',
    name: 'Footer Notice',
    description: 'Privacy and sharing notice (auto-generated)',
    mandatory: true,
    order: 100,
    formOrder: 100, // Not shown in form
    zone: ZONES.FOOTER,
    icon: 'mdi-information-outline',
    autoGenerated: true, // User doesn't fill this out directly
  },

  // === OPTIONAL SECTIONS ===
  PARTNERS: {
    id: 'partners',
    name: 'Partner Organizations',
    description: 'Collaborating institutions or organizations',
    mandatory: false,
    order: 30,
    formOrder: 4,
    zone: ZONES.SIDEBAR,
    icon: 'mdi-handshake-outline',
    config: {
      maxItems: 10,
    },
  },

  TIMELINE: {
    id: 'timeline',
    name: 'Project Timeline',
    description: 'Key milestones in your project development',
    mandatory: false,
    order: 40,
    formOrder: 5,
    zone: ZONES.SIDEBAR,
    icon: 'mdi-timeline-outline',
    config: {
      minItems: 2,
      maxItems: 10,
    },
  },

  IMPACT: {
    id: 'impact',
    name: 'Impact Summary',
    description: 'How your project benefits different audiences',
    mandatory: false,
    order: 50,
    formOrder: 6,
    zone: ZONES.SIDEBAR,
    icon: 'mdi-rocket-launch-outline',
    config: {
      minItems: 2,
      maxItems: 6,
    },
  },

  POSTER: {
    id: 'poster',
    name: 'Poster / Diagram',
    description: 'Research poster (PDF) or diagram (image)',
    mandatory: false,
    order: 60,
    formOrder: 7,
    zone: ZONES.MAIN,
    icon: 'mdi-image-outline',
    config: {
      allowedTypes: ['pdf', 'image'],
      maxSizeMb: 10,
    },
  },
};

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Get all sections as an array, sorted by order
 * @returns {Array} All sections sorted by display order
 */
export function getAllSections() {
  return Object.values(SECTIONS).sort((a, b) => a.order - b.order);
}

/**
 * Get only mandatory sections
 * @returns {Array} Mandatory sections sorted by order
 */
export function getMandatorySections() {
  return getAllSections().filter(s => s.mandatory);
}

/**
 * Get only optional sections
 * @returns {Array} Optional sections sorted by order
 */
export function getOptionalSections() {
  return getAllSections().filter(s => !s.mandatory);
}

/**
 * Get sections that appear in forms (excludes auto-generated)
 * @returns {Array} Form sections sorted by formOrder
 */
export function getFormSections() {
  return getAllSections()
    .filter(s => !s.autoGenerated)
    .sort((a, b) => a.formOrder - b.formOrder);
}

/**
 * Get a section by its ID
 * @param {string} sectionId - Section ID
 * @returns {Object|null} Section definition or null
 */
export function getSectionById(sectionId) {
  return Object.values(SECTIONS).find(s => s.id === sectionId) || null;
}

/**
 * Check if a section is enabled
 * @param {string} sectionId - Section ID to check
 * @param {string[]} enabledSections - Array of enabled section IDs
 * @returns {boolean} True if section is mandatory or in enabledSections
 */
export function isSectionEnabled(sectionId, enabledSections = []) {
  const section = getSectionById(sectionId);
  if (!section) return false;
  if (section.mandatory) return true;
  return enabledSections.includes(sectionId);
}

/**
 * Get enabled optional sections sorted by order
 * @param {string[]} enabledSections - Array of enabled section IDs
 * @returns {Array} Enabled optional sections sorted by order
 */
export function getEnabledOptionalSections(enabledSections = []) {
  return getOptionalSections()
    .filter(s => enabledSections.includes(s.id))
    .sort((a, b) => a.order - b.order);
}

/**
 * Get available (not yet enabled) optional sections
 * @param {string[]} enabledSections - Array of currently enabled section IDs
 * @returns {Array} Available optional sections sorted by order
 */
export function getAvailableOptionalSections(enabledSections = []) {
  return getOptionalSections()
    .filter(s => !enabledSections.includes(s.id))
    .sort((a, b) => a.order - b.order);
}

/**
 * Get sections for a specific zone
 * @param {string} zone - Zone identifier
 * @param {string[]} enabledSections - Array of enabled section IDs
 * @returns {Array} Sections in the zone that are enabled, sorted by order
 */
export function getSectionsForZone(zone, enabledSections = []) {
  return getAllSections()
    .filter(s => s.zone === zone && isSectionEnabled(s.id, enabledSections))
    .sort((a, b) => a.order - b.order);
}

/**
 * Calculate dynamic form section number
 * @param {string} sectionId - Section ID
 * @param {string[]} enabledSections - Array of enabled section IDs
 * @returns {number} The section number in the form
 */
export function getFormSectionNumber(sectionId, enabledSections = []) {
  const formSections = getFormSections();
  const visibleSections = formSections.filter(
    s => s.mandatory || enabledSections.includes(s.id)
  );
  const index = visibleSections.findIndex(s => s.id === sectionId);
  return index >= 0 ? index + 1 : 0;
}

/**
 * Get sections by their IDs, maintaining order
 * @param {string[]} sectionIds - Array of section IDs
 * @returns {Array} Sections sorted by order
 */
export function getSectionsByIds(sectionIds) {
  return sectionIds
    .map(id => getSectionById(id))
    .filter(Boolean)
    .sort((a, b) => a.order - b.order);
}

// =============================================================================
// DEFAULT CONFIGURATIONS
// =============================================================================

/**
 * Default enabled sections for new projects
 * These are pre-selected when creating a new project
 */
export const DEFAULT_ENABLED_SECTIONS = ['findings', 'partners', 'poster'];

/**
 * Recommended sections shown prominently in the configurator
 */
export const RECOMMENDED_SECTIONS = ['findings', 'partners', 'poster'];

// =============================================================================
// EXPORTS
// =============================================================================

export default {
  ZONES,
  SECTIONS,
  DEFAULT_ENABLED_SECTIONS,
  RECOMMENDED_SECTIONS,
  getAllSections,
  getMandatorySections,
  getOptionalSections,
  getFormSections,
  getSectionById,
  isSectionEnabled,
  getEnabledOptionalSections,
  getAvailableOptionalSections,
  getSectionsForZone,
  getFormSectionNumber,
  getSectionsByIds,
};
